#!/usr/bin/python3
# School Project for Scripting Languages class

import sqlite3
import csv
import sys


# ensures proper files are passed as args
if len(sys.argv) != 3:
	print("Usage: dbload CSVFILE DATABASEFILE")
	exit(1)


try:
	icsv = str(sys.argv[1])
except:
	print("Provide input csvfile")
	exit(1)


try:
	odb = str(sys.argv[2])
except:
	print("Provide output databasefile")
	exit(1)
	

# connects to db file
conn = sqlite3.connect(odb)
curs = conn.cursor()


# creates classes table
curs.execute('''DROP TABLE IF EXISTS courses''')
curs.execute('''CREATE TABLE courses
	(id TEXT, subjcode TEXT, coursenumber TEXT, termcode TEXT)''')


# creates students table
curs.execute('''DROP TABLE IF EXISTS people''')
curs.execute('''CREATE TABLE people
	(id TEXT PRIMARY KEY UNIQUE, lastname TEXT, firstname TEXT, major TEXT, email TEXT, city TEXT, state TEXT, zip TEXT)''')


# opens and reads the csv file
reader = csv.reader(open(icsv, 'r'), delimiter=',', quotechar='"')
counter = 0 
for row in reader:
	counter += 1 # skip first row
	if counter == 1:
		continue

	# splits the subjects and courses
	sc = row[5].split(" ")
	p = (row[0], row[1], row[2], row[3], row[4], row[7], row[8],row[9])
	c = (row[0], sc[0], sc[1], row[6])
	
	# only inserts if student doesn't already exist
	curs.execute("SELECT * FROM people WHERE id = '{0}'".format(row[0]))
	if not curs.fetchone():
		curs.execute('''INSERT INTO people(id, firstname, lastname, email, major, city, state, zip) VALUES (?,?,?,?,?,?,?,?)''', p)	
	curs.execute('''INSERT INTO courses (id, subjcode, coursenumber, termcode) VALUES (?,?,?,?)''', c)


conn.commit()
exit(0)

